CDGJ_MerriwaveTown_House_2_MapScripts::
	.byte 0


CDGJ_MerriwaveTown_House_2_EventScript_1::
# 4 "data/maps/CDGJ_MerriwaveTown_House_2/scripts.pory"
	faceplayer
# 5 "data/maps/CDGJ_MerriwaveTown_House_2/scripts.pory"
	msgbox CDGJ_MerriwaveTown_House_2_EventScript_1_Text_0
# 6 "data/maps/CDGJ_MerriwaveTown_House_2/scripts.pory"
	waitmessage
# 7 "data/maps/CDGJ_MerriwaveTown_House_2/scripts.pory"
	closemessage
# 8 "data/maps/CDGJ_MerriwaveTown_House_2/scripts.pory"
	release
	return


CDGJ_MerriwaveTown_House_2_EventScript_1_Text_0:
# 5 "data/maps/CDGJ_MerriwaveTown_House_2/scripts.pory"
	.string "OUTTA THE WAY! I'M EARNING ZONE MINUTES!$"
