CDGJ_MerriwaveTown_House_MapScripts::
	.byte 0


CDGJ_MerriwaveTown_House_EventScript_1::
# 4 "data/maps/CDGJ_MerriwaveTown_House/scripts.pory"
	faceplayer
# 5 "data/maps/CDGJ_MerriwaveTown_House/scripts.pory"
	msgbox CDGJ_MerriwaveTown_House_EventScript_1_Text_0
# 6 "data/maps/CDGJ_MerriwaveTown_House/scripts.pory"
	waitmessage
# 7 "data/maps/CDGJ_MerriwaveTown_House/scripts.pory"
	closemessage
# 8 "data/maps/CDGJ_MerriwaveTown_House/scripts.pory"
	release
	return


CDGJ_MerriwaveTown_House_EventScript_2::
# 12 "data/maps/CDGJ_MerriwaveTown_House/scripts.pory"
	faceplayer
# 13 "data/maps/CDGJ_MerriwaveTown_House/scripts.pory"
	msgbox CDGJ_MerriwaveTown_House_EventScript_2_Text_0
# 14 "data/maps/CDGJ_MerriwaveTown_House/scripts.pory"
	waitmessage
# 15 "data/maps/CDGJ_MerriwaveTown_House/scripts.pory"
	closemessage
# 16 "data/maps/CDGJ_MerriwaveTown_House/scripts.pory"
	release
	return


CDGJ_MerriwaveTown_House_EventScript_1_Text_0:
# 5 "data/maps/CDGJ_MerriwaveTown_House/scripts.pory"
	.string "We look forward to the Festival\nevery year! It's a nice way\pto give thanks to the little guys\nthat we love so dearly.$"

CDGJ_MerriwaveTown_House_EventScript_2_Text_0:
# 13 "data/maps/CDGJ_MerriwaveTown_House/scripts.pory"
	.string "I volunteer to make the soup every\nyear! I heard you're helping us get\pthe ingredients?$"
