CDGJ_MerriwaveTown_House_3_MapScripts::
	.byte 0


CDGJ_MerriwaveTown_House_3_EventScript_1::
# 4 "data/maps/CDGJ_MerriwaveTown_House_3/scripts.pory"
	faceplayer
# 5 "data/maps/CDGJ_MerriwaveTown_House_3/scripts.pory"
	msgbox CDGJ_MerriwaveTown_House_3_EventScript_1_Text_0
# 6 "data/maps/CDGJ_MerriwaveTown_House_3/scripts.pory"
	waitmessage
# 7 "data/maps/CDGJ_MerriwaveTown_House_3/scripts.pory"
	closemessage
# 8 "data/maps/CDGJ_MerriwaveTown_House_3/scripts.pory"
	release
	return


CDGJ_MerriwaveTown_House_3_EventScript_1_Text_0:
# 5 "data/maps/CDGJ_MerriwaveTown_House_3/scripts.pory"
	.string "One day, I woke up with a\nsimultaneous infection of\psalmonella and Campylobacter!\pI'm not sure why I just told\nyou that! Thanks though!$"
