CDGJ_Merriwave_Town_Festive_Pokemart_MapScripts::
	.byte 0


	.align 2
# 3 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
CDGJ_MerriwaveTown_Mart_Festive_Items:
# 4 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_POKE_BALL
# 5 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_GREAT_BALL
# 6 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_ULTRA_BALL
# 7 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_QUICK_BALL
# 8 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_DUSK_BALL
# 9 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_ORAN_BERRY
# 10 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_POTION
# 11 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_SUPER_POTION
# 12 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_HYPER_POTION
# 13 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_FULL_RESTORE
# 14 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_REVIVE
# 15 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_ANTIDOTE
# 16 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_PARALYZE_HEAL
# 17 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_AWAKENING
# 18 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_REPEL
# 19 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_FULL_HEAL
# 20 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_SUPER_REPEL
# 21 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_MAX_REPEL
# 22 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_FIRE_STONE
# 23 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_WATER_STONE
# 24 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_THUNDER_STONE
# 25 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_SHINY_STONE
# 26 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_DUSK_STONE
# 27 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_DAWN_STONE
# 28 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_SHINY_STONE
# 29 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_ICE_STONE
# 30 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_LEAF_STONE
# 31 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_MOON_STONE
# 32 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_SUN_STONE
# 33 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_DIRE_HIT
# 34 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_X_ACCURACY
# 35 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_X_ATTACK
# 36 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_X_DEFEND
# 37 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_X_DEFENSE
# 38 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_X_SP_ATK
# 39 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_X_SP_DEF
# 40 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_X_SPECIAL
# 41 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.2byte ITEM_X_SPEED
	.2byte ITEM_NONE

CDGJ_MerriwaveTown_Mart_Festive_Clerk::
# 45 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	lock
# 46 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	faceplayer
# 48 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	pokemart CDGJ_MerriwaveTown_Mart_Festive_Items
# 50 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	msgbox CDGJ_MerriwaveTown_Mart_Festive_Clerk_Text_0
# 52 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	release
	end


CDGJ_Merriwave_Town_Festive_Pokemart_EventScript_1::
# 57 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	faceplayer
# 58 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	msgbox CDGJ_Merriwave_Town_Festive_Pokemart_EventScript_1_Text_0
# 59 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	waitmessage
# 60 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	closemessage
# 61 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	release
	return


CDGJ_MerriwaveTown_Mart_Festive_Clerk_Text_0:
# 50 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.string "Enjoy the festival!$"

CDGJ_Merriwave_Town_Festive_Pokemart_EventScript_1_Text_0:
# 58 "data/maps/CDGJ_Merriwave_Town_Festive_Pokemart/scripts.pory"
	.string "The Pokemart stocks extra items during\nthe festival! I love stocking up!$"
