CDGJ_MerriwaveTown_House_4_MapScripts::
	.byte 0


CDGJ_MerriwaveTown_House_4_EventScript_1::
# 4 "data/maps/CDGJ_MerriwaveTown_House_4/scripts.pory"
	faceplayer
# 5 "data/maps/CDGJ_MerriwaveTown_House_4/scripts.pory"
	msgbox CDGJ_MerriwaveTown_House_4_EventScript_1_Text_0
# 6 "data/maps/CDGJ_MerriwaveTown_House_4/scripts.pory"
	waitmessage
# 7 "data/maps/CDGJ_MerriwaveTown_House_4/scripts.pory"
	closemessage
# 8 "data/maps/CDGJ_MerriwaveTown_House_4/scripts.pory"
	release
	return


CDGJ_MerriwaveTown_House_4_EventScript_2::
# 12 "data/maps/CDGJ_MerriwaveTown_House_4/scripts.pory"
	faceplayer
# 13 "data/maps/CDGJ_MerriwaveTown_House_4/scripts.pory"
	msgbox CDGJ_MerriwaveTown_House_4_EventScript_2_Text_0
# 14 "data/maps/CDGJ_MerriwaveTown_House_4/scripts.pory"
	waitmessage
# 15 "data/maps/CDGJ_MerriwaveTown_House_4/scripts.pory"
	closemessage
# 16 "data/maps/CDGJ_MerriwaveTown_House_4/scripts.pory"
	release
	return


CDGJ_MerriwaveTown_House_4_EventScript_1_Text_0:
# 5 "data/maps/CDGJ_MerriwaveTown_House_4/scripts.pory"
	.string "Don't tell the boss. I'm taking\na sick day today.\pSetting up the festival is so\nexhausting, I just don't wanna!$"

CDGJ_MerriwaveTown_House_4_EventScript_2_Text_0:
# 13 "data/maps/CDGJ_MerriwaveTown_House_4/scripts.pory"
	.string "I'm his boss. He thinks I can't\nhear him… … … … … …\pI'm also taking the day off.$"
