CDGJ_LakeArea_Mart_MapScripts::
	.byte 0


CDGJ_LakeArea_Mart_EventScript_1::
# 5 "data/maps/CDGJ_LakeArea_Mart/scripts.pory"
	faceplayer
# 6 "data/maps/CDGJ_LakeArea_Mart/scripts.pory"
	msgbox CDGJ_LakeArea_Mart_EventScript_1_Text_0
# 7 "data/maps/CDGJ_LakeArea_Mart/scripts.pory"
	waitmessage
# 8 "data/maps/CDGJ_LakeArea_Mart/scripts.pory"
	closemessage
# 9 "data/maps/CDGJ_LakeArea_Mart/scripts.pory"
	release
	return


CDGJ_LakeArea_Mart_EventScript_2::
# 13 "data/maps/CDGJ_LakeArea_Mart/scripts.pory"
	faceplayer
# 14 "data/maps/CDGJ_LakeArea_Mart/scripts.pory"
	msgbox CDGJ_LakeArea_Mart_EventScript_2_Text_0
# 15 "data/maps/CDGJ_LakeArea_Mart/scripts.pory"
	waitmessage
# 16 "data/maps/CDGJ_LakeArea_Mart/scripts.pory"
	closemessage
# 17 "data/maps/CDGJ_LakeArea_Mart/scripts.pory"
	release
	return


CDGJ_LakeArea_Mart_EventScript_1_Text_0:
# 6 "data/maps/CDGJ_LakeArea_Mart/scripts.pory"
	.string "I love this resupply point!\nSuper convenient!$"

CDGJ_LakeArea_Mart_EventScript_2_Text_0:
# 14 "data/maps/CDGJ_LakeArea_Mart/scripts.pory"
	.string "I wish they sold HM03 Surf here...$"
